version: 2.1
orbs:
  node: circleci/node@3.0.0
  
jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests
  
workflows:
  node-tests:
    jobs:
      - test
